rmq:
  start_with_api: true
  prefetch:

  connection:
    host: localhost
    port: 5672
    login:  guest
    password:  guest

  test_queue:
    params:
      name: test_item_cnv
      durable: True
    bind:
      exchange: state_service
      routing_key: 'Event.#'
